spring:
  datasource:
    url: jdbc:postgresql://sa-coding-hackathon.cluster-chur8opkdp9u.us-east-1.rds.amazonaws.com:5432/postgres
    username: legendofjava
    password: ${POSTGRES_SECRET}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
s3:
  bucket:
    name: bucket-hackathon-test-12983765123
    accessKey:
    secretKey: