spring:
  datasource:
    url: jdbc:h2:mem:demo
    username: legendofjava
    password: ${POSTGRES_SECRET}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: NON_NULL
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS:LegendOfJavaSACoding@gmail.com} # This is for demo only, will probably need a business account
    password: ${GMAIL_PASSWORD:supersecurepassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    session:
      timeout: 20m  # This is a max inactive time, it'll only kill the session after 20 minutes of complete inactivity
      
logging:
  level:
    io.legendofjava.sacoding: ${LOG_LEVEL:INFO}
    
s3:
  bucket:
    name: ${BUCKET_NAME:some-bucket}

